name: "Deploy to nuget"

on: 
  push:
   tags: 
    - 'v*'

env:
 PROJECT_PATH: 'CSharpFancyExtensions/CSharpFancyExtensions.csproj'
 PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}\output
 NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
 deploy:
   name: 'Deploy'
   runs-on: 'windows-latest'
   steps:
    name: 'Checkout'
    uses: 'actions/checkout@v2'

    name: 'Install dotnet'
    uses: 'actions/setup-dotnet@v1'
    with:
     dotnet-version: '5.0.3'
