name: "Deploy to nuget"

on: 
  push:
   tags: 
    - 'v*'

env:
 PROJECT_PATH: 'CSharpFancyExtensions/CSharpFancyExtensions.csproj'
 PACKAGE_OUTPUT_DIRECTORY: ${{github.workspace}}\output
 NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet run --project NetLicensingClient-demo
